platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target "TwitterClient" do
    pod 'SwiftyJSON'
    pod 'MAGCoreData', :git => 'https://github.com/MadAppGang/MAGCoreData.git'
    pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
    pod 'Toast', '~> 3.0'
    pod 'JGProgressHUD', '~> 1.2.7'
end

